Complete weather station with ESP32 using BLE and WiFi
ElectronicCats/meteoritoboard pull request #2
Opened 2018-07-23 23:13 UTC by BrandonAre

2018-07-23 23:27 UTC, sabas1080 commented
Por mi esta bien, adelante

2018-07-24 15:40 UTC, sabas1080 requested changes

2018-07-24 15:40 UTC, sabas1080 commented on Firmware/meteorito/meteorito.ino
> +    //cont = 0;
Este comentario es inncesario

2018-07-24 18:33 UTC, chio7896 commented
Lo única observación que tengo es que en el código hay que definir los margenes que separan cada función, e if y else.

2018-07-24 19:27 UTC, sabas1080 approved these changes

2018-07-24 19:28 UTC, sabas1080 commented
Voy hacer merge

Gracias @BrandonAre

2018-07-24 19:28 UTC, merged